admin_posts_list: # nom de la route
  path: /admin/posts # chemin dans l'URL de la route
  controller: App\Controller\Admin\ArticleController::listPosts # fonction avec le chemein du controller qui est associée à cette route

admin_app_article:
  path: /admin/article
  controller: App\Controller\Admin\ArticleController::index

admin_app_category:
  path: /admin/category
  controller: App\Controller\Admin\CategoryController::index

admin_categories_list:
  path: /admin/categories
  controller: App\Controller\Admin\CategoryController::listCategories

admin_category_show:
  path: /admin/category/{id}
  controller: App\Controller\Admin\CategoryController::showCategory

admin_update_category:
  path: /admin/update/category/{id}
  controller: App\Controller\Admin\CategoryController::updateCategory

admin_create_category:
  path: /admin/create/category
  controller: App\Controller\Admin\CategoryController::createCategory

admin_delete_category:
  path: /admin/delete/category/{id}
  controller: App\Controller\Admin\CategoryController::deleteCategory
