posts_list: # nom de la route
  path: /posts # chemin dans l'URL de la route
  controller: App\Controller\ArticleController::listPosts # fonction avec le chemein du controller qui est associée à cette route

app_article:
  path: /article
  controller: App\Controller\ArticleController::index

app_category:
  path: /category
  controller: App\Controller\CategoryController::index

categories_list:
  path: /categories
  controller: App\Controller\CategoryController::listCategories

category_show:
  path: /category/{id}
  controller: App\Controller\CategoryController::showCategory

update_category:
  path: /update/category/{id}
  controller: App\Controller\CategoryController::updateCategory

create_category:
  path: /create/category
  controller: App\Controller\CategoryController::createCategory

delete_category:
  path: /delete/category/{id}
  controller: App\Controller\CategoryController::deleteCategory
