posts_list: # nom de la route
  path: /posts # chemin dans l'URL de la route
  controller: App\Controller\ArticleController::listPosts # fonction avec le chemein du controller qui est associée à cette route

app_article:
  path: /article
  controller: App\Controller\ArticleController::index
